name: Deploy Prod

on:
  push:
    branches:
      - prod

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Use Checkout
        uses: actions/checkout@master
        with:
          persist-credential: false
      
      - name: Use NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Install Dependencies
        uses: borales/actions-yarn@master
        with:
          cmd: install

      - name: Build SSR
        uses: borales/actions-yarn@master
        with:
          cmd: build

      - name: Setup GCP
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy
        uses: google-github-actions/deploy-appengine@main
